### ISSUE TITLE
Any plans for a Android app?

### ISSUE THREAD

**Issue by DillFrescott** [HACKERALERT/Picocrypt#100]
Would love to install this as an .apk and encrypt on the go!

**Comment by HACKERALERT** [comment]
Sorry about the closing, I accidentally hit it button.

No, I don't plan to support Android because it is very different from desktop systems and difficult to work with as I am not very experienced with it. The GUI bindings that Picocrypt uses also doesn't support Android, so I can't compile it for Android in the first place. However, Pico is open source so it is possible someone will create an Android port in the future.

**Comment by DillFrescott** [comment]
Its ok.

Gotcha, thought it might be worth asking haha.

One last thing, would it be possible to make a self extracting archive, where picocrypt is bundled in with the encrypted file(s), so you can just run the file and not have to have picocrypt downloaded.

It might make sharing files easier if its all included.

Let me know what you think!

**Comment by HACKERALERT** [comment]
Self extracting archives are a little complicated for a relatively high level language like Go. I know 7-Zip has the functionality, but 7-Zip is written in C which is better for low level functionality like SFX. So I don't think it would be feasible. You can always just zip Picocrypt with the volume and send it, since Pico is small and only adds a 2MB overhead :)

**Comment by DillFrescott** [comment]
Okay! Thank you! I'm going to close this issue for now too!
