### ISSUE TITLE
Does Picocrypt have any protection against brute force cracking? For example, prevent cloud supercomputer cluster cracking and other advanced ways

### ISSUE THREAD

**Issue by ZhuningS** [HACKERALERT/Picocrypt#104]
Does Picocrypt have any protection against brute force cracking? For example, prevent cloud supercomputer cluster cracking and other advanced ways
(like slow hashing or IOS cracking delay, hardware dog, lockdir restriction, physical partition, multiple compound encryption, obfuscation combination, split split, hidden decryption entry)
Like https://www.catpasswd.com
Catpasswd.com introduction:
Online AI matches highly relevant alternative passwords (Google also has an AI chip TPU)
24 - hour automatic file password recovery service
Advanced APS(Adcance Password Search) precise Password matching Search algorithm
Online cloud supercomputer cluster
In 2011, rar GPU Password Recovery (RAR GPU Password Recovery) was used to crack the rar Password, which greatly improved the efficiency of brute force cracking

In 2011, someone used brute force to crack the 14-digit password set by himself in 6 months.
2010: rar password cracking tool with graphics card (RAR GPU Password Recovery): allows you to use GPU to brute force passwords, Radeon HD 5770 can perform 3.3 billion operations per second
The Radeon HD 5770 can crack a five-digit password "fjR8n" in under a second...  
If you have four HD 5970s, the speed of cracking will reach 33.1 billion times per second, and the CPU we generally use is only about 9.8 million times per second, and it must take 24 seconds of computing time!
For the six-digit password "pYDbL6", the CPU takes 90 minutes and the GPU four seconds, while the seven-digit password "fh0GH5h" takes four days for the CPU and 17 minutes and 30 seconds for the GPU. If it is eight or nine For a password with more than 10 digits and random mixed case, the GPU needs to count 48 days, while the CPU needs to count 43 years.

**Comment by HACKERALERT** [comment]
Yes, Picocrypt is arguably the strongest encryption tool available due to the use of Argon2, a memory-hard, high-intensity key derivation function. When you encrypt some files with Picocrypt, it will use Argon2 with 4 passes, 1 GiB memory, and 4 threads to derive the main encryption key. The 1 GiB memory requirement will make bruteforce cracking impossible because not only do you need insanely fast computers to do the computations, but you also need an insane amount of high-speed memory to meet the Argon2 requirement. To crack 1000 passwords per second, you would need at least 1 TiB of memory, which is more memory than the average disk these days. To reach the 33.1 billion passwords per second you mentioned, you would need about 33.1 exabytes of RAM, 33.1 billion consumer CPUs, and more energy than the energy consumption of the entire world just to get a chance at cracking a Picocrypt volume. Of course, all of this is theoretical and it would take more energy than exists in our universe to practically crack a Picocrypt volume unless there is a flaw discovered in Argon2 or ChaCha20.

**Comment by HACKERALERT** [comment]
Closing for now, see message on Reddit or Discord for more information.
