### ISSUE TITLE
Feature suggestion: A "secure delete" function when deleting input files after encryption

### ISSUE THREAD

**Issue by nivomi** [HACKERALERT/Picocrypt#108]
This may be out of scope/impractical to implement reliably across different platforms and hardware (and I understand that it's better to _not_ do something than to do it poorly/unreliably, especially in security contexts) but having a 'secure delete' function instead of just a filesystem delete could be a useful feature. As it stands, the files may still be in a recoverable, unencrypted state post-delete.

An additional issue with this feature is that 'secure delete' operations on SSDs are not really possible, and thus the application would have to warn users of this.

Instead of putting in the feature work, it might be better to just warn users of the possibility of recovery when using the 'delete' function, to allow them to manage their threat models in an informed way.

**Comment by HACKERALERT** [comment]
The UI currently shows "Delete files", so I guess it is good enough since it doesn't say "Shred files" or "Securely delete files", just "Delete files". The feature is mostly inspired by 7-Zip's option to delete files after compression and 7-Zip doesn't mention anything about shredding, and I don't think it is necessary to "warn" users about it since as you have said, there really is no such thing as secure delete anyways.

**Comment by HACKERALERT** [comment]
Closing for now, see message on Reddit or Discord for more information.
