### ISSUE TITLE
Configuration persistence until closed

### ISSUE THREAD

**Issue by Fraxlin** [HACKERALERT/Picocrypt#109]
Currently every time you encrypt some resources, after the job is done, the program resets itself to the default configuration (no password or keyfile set, no options checked, etc.). This behavior is fine, but sometimes there are some scenarios which is not, for example when you have to encrypt multiple files each one separately but with the same configuration (same password\keyfile and settings).
Right now I have to set the same settings again and again for each elaboration: it would be nice if Picocrypt could remember password/keyfile and other settings until closed and not "per-elaboration", so that if you have to encrypt hundreds of files separately you can do it mechanically with a simple drag & drop without thinking too much and decreasing the risk of mistakes. Eventually this behavior can be made optional.

**Comment by HACKERALERT** [comment]
Interesting suggestion. Under what case would you need to encrypt hundreds of files separately, though? If there is a need to encrypt that many files individually, I think you may need to reconsider your plan :)

Picocrypt is meant to be simple, so it makes most sense to just reset everything so that there isn't any room for errors (forgetting to remove a keyfile, etc.). Under most cases, you shouldn't need to do a lot manually.

**Comment by HACKERALERT** [comment]
Closing for now, see message on Reddit or Discord for more information.
