### ISSUE TITLE
Add button to select file to encrypt

### ISSUE THREAD

**Issue by lord-re** [HACKERALERT/Picocrypt#115]
Picocrypt is nice with its little GUI but it can't work if you can't drag'n'drop files.
If you use a linux distro without a file manager you can't use it.

It would be quite nice to change the "clear" button to a "select" button which would open a file chooser.
When the file is chosen, the button could become a "clear" button.

That way you won't have to change the window geometry or anything else.

**Comment by Benson665** [comment]
Ok am in it,thanks

**Comment by HACKERALERT** [comment]
If you don't have a file manager installed, the file chooser dialog won't work either because it depends on the system file manager which isn't installed. I think if you don't have a file manager on your system in 2022, you have greater things to worry about than if I can add a file chooser to Picocrypt 😅

**Comment by HACKERALERT** [comment]
Ah okay, pardon my incompetence in Linux. Still though, I think not having a file manager is a 0.0001% sort of thing, so I don't think making the potentially bug-inducing changes would be worth the extremely small number of cases where it is useful. I appreciate your request though :P
