### ISSUE TITLE
Plausible Deniability / Hidden Containers

### ISSUE THREAD

**Issue by realdep** [HACKERALERT/Picocrypt#117]
It would be really useful to have something like veracrypts hidden volume feature in case you are forced to open the container.

**Comment by Kispisti** [comment]
https://www.reddit.com/r/Picocrypt/comments/ux7rmw/goodbye/?utm_medium=android_app&utm_source=share

**Comment by HACKERALERT** [comment]
That's been requested before, but due to the way Picocrypt is designed, this is not possible. The reason hidden volumes are possible within VeraCrypt is because it preallocates a volume and fills it with random data (which cannot be differentiated from hidden and encrypted data), whereas Picocrypt only encrypts the files themselves and thus doesn't have a fixed volume size. Hidden volumes wouldn't work with Picocrypt because any files you store in the hidden section would inflate the volume size, and when decrypting the volume, the output size wouldn't match the size of the volume and you would know there is hidden data (thus breaking the plausible deniability aspect). I could start adding 1 MiB of random data at the end of every Picocrypt volume, which you could then use to plausibly store up to 1 MiB of hidden files, but that's too complicated and doesn't really follow Picocrypt's goal of being simple.
