### ISSUE TITLE
Build from the source

### ISSUE THREAD

**Issue by leestarb** [HACKERALERT/Picocrypt#119]
The real man always building programs he needs from source code. But i dont see a way to make install with this! :)

**Comment by HACKERALERT** [comment]
Picocrypt is portable so there's no standard way to install it other than the .deb. You didn't tell my what OS you're on. I assume Linux? If you're on a Debian-based distro, you can go to issue #84 and download AppImage-Deb-Builder.zip which I've reacted to with a 👀 . Run `Compile.sh` which is inside and it'll build a .deb from source which you can install. Otherwise, I don't know how to do it since Picocrypt was not meant to be installed :)

**Comment by CrazycatASG** [comment]
You don't build it with make. Picocrypt is built with `go build`.

**Comment by HACKERALERT** [comment]
Oh, @leestarb meant `make install`. I didn't recognize that since I don't code in C. Yeah, as @CrazycatASG mentioned, Picocrypt is written in the Go language, so you should `go build Picocrypt.go` to build Picocrypt from source. If you look into the `src/` directory, there are detailed instructions.

**Comment by HACKERALERT** [comment]
I'll close this issue now as the question has been answered and the answer is pretty straightforward. Feel free to reopen this issue if needed, @leestarb! Thanks.

**Comment by leestarb** [comment]
Thanks, @HACKERALERT !
