### ISSUE TITLE
Will Picocrypt still be getting a security audit? 

### ISSUE THREAD

**Issue by CrazycatASG** [HACKERALERT/Picocrypt#121]
I noticed that you stopped taking donations for Picocrypt. Will it still be getting a security audit?

**Comment by HACKERALERT** [comment]
Of course! I stopped taking personal donations since I don't need them anymore and I want to put full focus on funding for the audit. So, I removed my PayPal from the Donations section and put a note, but the audit is still being funded on Open Collective and the Funding section near the top of the README is still there. Sorry for any confusion :)

**Comment by CrazycatASG** [comment]
No problem. Thanks for the help!
