### ISSUE TITLE
build fails on i386

### ISSUE THREAD

**Issue by nunotexbsd** [HACKERALERT/Picocrypt#127]
1.30 fails to build on i386 arch:

`Picocrypt.go:53:11: cannot use 1 << 40 (untyped int constant 1099511627776) as int value in variable declaration (overflows)`

Picocrypt FreeBSD [port](https://www.freshports.org/security/picocrypt/) 1.25 builds fine, any hints?

Thanks

**Comment by HACKERALERT** [comment]
Ah, 32-bit systems aren't supported by Picocrypt. As a quick explanation, integers in Go are by default the number of bits of the system. So on 32-bit systems, Go's integers are 32-bit. In the error message, 1<<40 is a 40-bit number, which is greater than the 32-bit support, so it fails to build, hence the message about overflows. There's no obvious solution other than to use a 64-bit system since 40 bits is less than 64 bits.

If you insist on a solution, however, a hacky one would be to replace 1<<40 with 1<<30 on line 53. Doing this would break the file splitting feature for files greater than 1 TiB, but it's unlikely you'll be encrypting more than 1 TiB of data, so it is a reasonable compromise. tl;dr: Picocrypt is 64-bit only.

Let me know if that helps!

**Comment by nunotexbsd** [comment]
Hello,

Thanks for explanation, I will mark this port only for 64-bit archs.

Cheers

**Comment by HACKERALERT** [comment]
Awesome, thank you so much for updating the port! Glad to see it on the latest release again.

**Comment by Benson665** [comment]
It's my pleasure
