### ISSUE TITLE
Insufficient disk space

### ISSUE THREAD

**Issue by Yoanndp** [HACKERALERT/Picocrypt#128]
Hello, I'm trying to encrypt a file, and I'm getting this error
 ![error ](https://user-images.githubusercontent.com/13591243/192519207-a58d08fc-b692-4b46-ad48-fec95a9fcc82.png)
but I got 316Gb of free space on my hard drive. Is that a bug, or am I doing something wrong ?

**Comment by HACKERALERT** [comment]
Hmm, that shouldn't be happening. Try the following and let me know which ones work:
- A different file
- Multiple files and folders
- Saving in another location
- Not using any advanced options
- Moving the file to another location such as your Documents before encrypting

**Comment by Yoanndp** [comment]
It worked when I tried to back it up to another disk (network disk with 5 TB free). I used exactly the same settings: weird !

**Comment by HACKERALERT** [comment]
That is weird indeed. Play around with it a little and let me know if you find any more information. It may just be a one-time issue 🤷

**Comment by Yoanndp** [comment]
Alright ! I'll close this issue right now. If I can somehow replicate this bug, I'll reopen it 😉

**Comment by Yoanndp** [comment]
Hello, I think I found the error related to this problem. This message is displayed when the file to be encrypted is in use by another process. The error message displayed is therefore incorrect: it might be appropriate to display a different message ?

**Comment by HACKERALERT** [comment]
Interesting, because in my code, the insufficient space error only shows when an issue occurs while writing to a file, not when reading from a file. Can you send me steps to reproduce the issue, or even better, a video of the issue? That'll help me figure out what's going on. Thanks!

**Comment by Yoanndp** [comment]
To give you more context, I was making a copy of my emails (locally) to a cloud service. The idea was to encrypt my data for more control over my data. With this in mind, I tried to encrypt the following file: 
> C:\Users\<username>\AppData\Local\Microsoft\Outlook\<your_email_address>.ost (which contains all the mails).

However, the MS Outlook application was running on my PC when I tried to encrypt this file. Once the application was closed, the encryption was successful. This is the behavior that makes me believe that there is this error when another process uses a file! I hope this background allows you to try it on your side. If this is not enough, I can send you a video clip, but I prefer to avoid it if possible, because it will contain my professional e-mail address.

**Comment by HACKERALERT** [comment]
I still can't reproduce the issue lol. Where are you saving the output? Perhaps the Outlook folder has write protection so if you try to write the output volume to it, it won't work. Try changing the output to your Downloads folder and let me know how that goes.

**Comment by Yoanndp** [comment]
I am saving the file on the desktop from the beginning

**Comment by HACKERALERT** [comment]
Yeah I took a closer look through the code and I still don't see where anything could go wrong. The only way for the error to show is if there's a problem when writing to a file, so in your case, there must be an issue with writing to the volume. The error shouldn't occur from reading the file because there's a separate error message to handle reading and writing permission errors. Somehow as you have mentioned, when Outlook is closed, it just seems to work. Is it just Outlook that gives you this problem? Because if other software works fine and Outlook is just an outlier, we probably don't need to worry about this issue too much. I don't really think this is something I can fix from my end :)

**Comment by Yoanndp** [comment]
Hello, I replicated the bug on my wife's laptop. I discovered that using Reed-Solomon + Compress file (and the context I explained above), the error appears. Can you try using this setup ?

**Comment by HACKERALERT** [comment]
To be honest, this seems like too much of an edge case and I don't think it's worth looking into further. I searched up the issue with .ost files and it seems like it's a somewhat common issue with Outlook specifically. Since the only thing "wrong" here is the error message, and Picocrypt still functions correctly and catches the error, I say we just leave as is since it's unlikely to be a big issue. Let me know what you think.

**Comment by Yoanndp** [comment]
It doesn't change anything for me, I opened this ticket to inform you about the problem and explain that the error message was incorrect. Now, if you decide not to handle this case, then I think there is no need to continue discussing this topic.
