### ISSUE TITLE
Doesn't start on Windows 10

### ISSUE THREAD

**Issue by Akhilesh-T** [HACKERALERT/Picocrypt#129]
Hi,

This software has never started on my Windows. Today I decided to give it another try and download the latest version. It still doesn't start. I've also tried to run it as administrator. I don't understand what's wrong.

I'm using **Windows 10.0.19044 Build 19044**

Edit: I tried the version 1.29 of `Picocrypt-NoGL.exe` and it WORKS

**Comment by potassiumchloride** [comment]
I confirm this behavior. Version 1.30 does not start on Windows 8.1 either. Version 1.29 of `Picocrypt-NoGL.exe` runs without problems.

**Comment by HACKERALERT** [comment]
The current setup is a little messy, so here's a quick breakdown:
v1.30 Picocrypt.exe requires DirectX12
v1.29 Picocrypt.exe requires OpenGL
v1.29 Picocrypt-NoGL.exe requires nothing
So if v1.30 doesn't work on your system, it doesn't have DirectX 12.
If v1.29 Picocrypt.exe doesn't work, your system doesn't have OpenGL 3.2
v1.29 Picocrypt-NoGL.exe will work on all systems.

For the next release (v1.31), I will be going back to OpenGL since it seems that a lot of systems don't have DirectX 12 yet. However, I will not release a NoGL version because OpenGL 3.2 was released in 2009 and any modern system with up-to-date drivers will support it.

@Akhilesh-T Try Check your CPU manufacturer for specs on your CPU. It will most likely support OpenGL 3.2 or above unless it's an ancient CPU. If your CPU does support OpenGL 3.2 or higher, install the official drivers for it and Picocrypt will work after a reboot. If you can't find the official drivers, try installing Driver Booster which will automatically update all drivers for your system (beware of adware during installation).

@potassiumchloride Same thing as what I recommended for @Akhilesh-T. However, I only officially support Windows 10 and 11, so running 8.1 is not a great idea, especially since security updates will stop being provided by Microsoft soon.

In either case, you can use v1.29 Picocrypt-NoGL, which is fully compatible with all current and all future releases. Let me know if you have any questions!

**Comment by potassiumchloride** [comment]
Thanks a lot for the detailed explanation - very much appreciated! I'll keep on running Windows 8.1 as long as it receives official security updates (which is going to end soon anyway) and then consider upgrading to Windows 10 Enterprise.

For now I rely on your NoGL.exe under Windows 8.1 because Dell/Microsoft do only support Windows 10 (and higher) on my current hardware. (I managed to install Windows 8.1 with some kind of "force" on the hardware because at that time Windows 10 was not allowed in our environment.)

**Comment by HACKERALERT** [comment]
I just released v1.31 which goes back to OpenGL. I'll close this issue for now since I've done what I can on my end. Feel free to re-open if you have anything to discuss!
