### ISSUE TITLE
Is it possible to just do reed-solomon and not encrypt?

### ISSUE THREAD

**Issue by dillfrescott** [HACKERALERT/Picocrypt#131]
This would be useful for times when the drive is already encrypted or what not, but you still need the erasure coding!

**Comment by HACKERALERT** [comment]
I don't officially support Reed-Solomon-only volumes, but you can just use a space as a password and basically achieve the same thing. You can also leave a password hint with the password since in this case, you don't need any security and just need the erasure coding. I feel like allowing Reed-Solomon without a password will be a footgun for some people, so I think I'll keep the password requirement.

**Comment by dillfrescott** [comment]
Okay! Makes sense. Thank you!
