### ISSUE TITLE
Provide Right Click Context Menu

### ISSUE THREAD

**Issue by Sn0whax** [HACKERALERT/Picocrypt#133]
I understand the app is considered complete, but hear me out.

A right click context menu would allow for the following:
1. Easier encryption of folders/(creating zip, then encrypting it) (Associating with file types)
2. More adoption/ease of use (More adoption)
3. Allowing an "ecosystem" of Picocrypt where we can have our xchacha20 encrypted files+compression accessible without locating the executable. This would encourage people to use Picocrypt over 7zip, etc in many cases.

**Comment by HACKERALERT** [comment]
This has been suggested before and I have tried it. It's a lot easier said than done though; getting context menu support on Windows is hard enough, and I don't even want to think about having to deal with the hundreds of Linux file managers that each have their own set of interfaces and extensions. Also, messing with context menus will no longer make Picocrypt portable and isolated since system modifications are required to set up the context menu. It will also require administrator privileges and involve copying files into system folders.

If you can write the cross-platform code that does it for me, I will consider it. Otherwise, I don't feel the time and effort that I would put into this is worth it, especially since Picocrypt is designed to be portable and self-contained.

**Comment by Kispisti** [comment]
I understand it...
But at least ,please make Picocrypt accept input filename from cmd line. For example: picocrypt.exe 1.dat 
By this way we can make our own context menu integration.

**Comment by HACKERALERT** [comment]
I don't intend to add any CLI features, sorry. If you would like a command line encryption tool, you can check out age or Kryptor.

**Comment by HACKERALERT** [comment]
In a spark of motivation, I've finally added a simple CLI to Picocrypt! Let me know what you think.

https://github.com/HACKERALERT/Picocrypt/tree/main/cli
