### ISSUE TITLE
At Risk Of Being Viewed Negatively

### ISSUE THREAD

**Issue by 0bvio** [HACKERALERT/Picocrypt#149]
I may be at risk of being viewed negatively by coming here to ask this... but... I would love to get in contact with you and I have been having trouble doing so through any other medium.  I am not sure how to contact someone on GitHub other than through this form... and Reddit wouldn't allow me to message you, let alone follow you.  I have questions regarding Picocrypt and a private privacy project (oh, the irony!)

My email is sly@0bv.io

**Comment by HACKERALERT** [comment]
I didn't really bother including personal contacts because for most people, if they have a question or bug, they will open an issue and that's usually sufficient. I also don't want too much spam either. If you look closely though, you'll find my email in the SECURITY.md and you're free to email me privately. For now I think the current setup is fine, but I will reevaluate if it becomes a big issue. Thanks :)

**Comment by 0bvio** [comment]
Thank you for the information!

And apologies for any miscommunication

**Comment by 0bvio** [comment]
Cant actually find the SECURITY.md file as mentioned, so if its obviously placed, I am obviously blind.

**Comment by HACKERALERT** [comment]
@0bvio haha no worries, here you are:
https://github.com/HACKERALERT/Picocrypt/blob/main/SECURITY.md
