### ISSUE TITLE
Please bump golang.org/x/sys dependency to enable build on riscv64-freebsd

### ISSUE THREAD

**Issue by clausecker** [HACKERALERT/Picocrypt#151]
Your custom-vendored `golang.org/x/sys` fork is too outdated to support riscv64-freebsd.  Please rebase it on the current version (e.g. `v0.6.0`) to enable a build on this new platform.

**Comment by HACKERALERT** [comment]
I don't think riscv support is important, since nobody uses it yet. Besides, there are probably other dependencies that don't support riscv either. Pico already supports amd64 natively on Windows, macOS, and Linux, and arm64 through the emulation layers built into Windows 11 and macOS. I think that's good enough. Linux is too broad to worry about every architecture, and I'll leave it to Wine to work on these systems. Thanks for reporting though.

**Comment by clausecker** [comment]
The only thing that prevents portability in this application are your weird hacked forks of standard dependencies.  Not sure why you insist on making the application less portable than it naturally is.

Btw, this is for FreeBSD on which the application builds just fine (though not on all architectures as you ship modified outdated dependencies that break support which would otherwise work just fine).

**Comment by HACKERALERT** [comment]
Yeah, portability is not a huge concern for this project. As long as it runs fine on Windows, macOS, and "standard" Linux distros and architectures, security and reliability are more important and so offline forks are preferable. Wine can do the work for the other cases. I definitely appreciate the hard work port maintainers do to make things work everywhere, so don't take this choice personally😄
