### ISSUE TITLE
Enhancement: It would be great to be able to switch languages.

### ISSUE THREAD

**Issue by MasterixCZ** [HACKERALERT/Picocrypt#159]
Hi, as the title says, it would be great to have Picocrypt in multiple languages. You could add some sort of community translation option to the app. I could translate the app into my language myself :) (Czech). 
Because not everyone is comfortable with English or doesn't understand it, but would like to use Picocrypt while _fully_ understanding the application interface, which is quite important in an encryption application.

**Comment by HACKERALERT** [comment]
There used to be translations, but I stopped maintaining them and
eventually deleted them because they needed constant PRs to stay up to
date. Every time a new translation was added, I would have to create a new
release for the new translation to show in the program. Every time I added
something to the README, all translations would need changes. For the
README, translators exist and browsers will typically do it automatically,
so it's not necessary. For the program itself, it's simple enough and well
documented in the README that it should be fine for most people.

**Comment by MasterixCZ** [comment]
Well there must be a better way than always updating every translation. A lot of Github projects are using Transifex or some other service (I don't know how they work for developers but I translated many projects through them.)

**Comment by MasterixCZ** [comment]
Okay, then.

**Comment by HACKERALERT** [comment]
Thanks for understanding!
