### ISSUE TITLE
Add Localization Support

### ISSUE THREAD

**Issue by umitseyhan75** [HACKERALERT/Picocrypt#16]
Not just for graphical user interface but also for encoding/characterset. As you may see in the screenshot below some letters (Turkish ones in my case) becomes to question marks.
Also, I want to conribute as a translator, so waiting for it.

![Adsız](https://user-images.githubusercontent.com/43583375/126030887-10fcf56a-74ef-4bea-9270-a7e7d8034a62.png)

**Comment by HACKERALERT** [comment]
Hi @umitseyhan75, thank you very much for reaching out! The GUI framework I use is giu (https://github.com/AllenDang/giu). You're currently using v1.13 of Picocrypt, which uses v0.5.4 of giu. In that version, giu doesn't have multilingual support yet, as Go is a new language, and GUIs in Go are even newer stuff. I'm looking into finding a font that covers all character sets that I can use in Picocrypt. That way, any character can be displayed on the GUI. Combining a universal font along with the latest version of giu, which has multilingual support, we should be good to go. In terms of encoding/character sets, this actually isn't a problem at all because Picocrypt reads from files as binary, not as UTF-8 or ANSI or something like that. So the only big deal here is getting the GUI to be multilingual. I'm really happy that you would like to contribute as a translator. Please let me get things sorted out and set up, and then you can start translating! Would you like to translate the GUI, the homepage, both, or some parts of both? Anything is fine with me, but let me know so that I can prepare and get things ready. Thank you!

**Comment by umitseyhan75** [comment]
I can translate both readme.md and gui, jsut provide me the localization texts. Waiting for it!

**Comment by HACKERALERT** [comment]
You are awesome! Give me a few hours and I'll get back to you. In the meantime, I think I've figured out how to make Picocrypt display all language characters! I found Google's Noto Sans font which contains over 500 languages, so that should be able to cover 99.9% of all countries and languages. Can you try the alpha version of Picocrypt 1.14 that I've attached and let me know if Turkish characters show up correctly? Thank you :)

[Picocrypt.zip](https://github.com/HACKERALERT/Picocrypt/files/6835244/Picocrypt.zip)

**Comment by umitseyhan75** [comment]
Yeap, it works like a charm!

**Comment by HACKERALERT** [comment]
Nice! I'll start working on localization and I'll notify you when I'm ready for you help.

**Comment by umitseyhan75** [comment]
There is one thing I want to mention, the gui in 1.14 does not fit completely to the window, I need to scroll down a bit. Besides I can not resize the window either.

**Comment by HACKERALERT** [comment]
Yup, I know, it's the same for me. I've been changing the UI a little and haven't gotten a chance to update the window size, since it's an alpha preview and wasn't meant to be public yet. I just gave it to you to test out character support, so the issue will be fixed in the official 1.14 release. Don't use the alpha release for anything important, because it has bugs and issues I haven't gotten to yet.

**Comment by umitseyhan75** [comment]
Okay, If we need to consider the time zone difference between us, I think I'll check up your work tomorrow. Good bye for now!

**Comment by HACKERALERT** [comment]
Alright. For your reference, I'm Eastern time, so it's 4:48 PM right now.

**Comment by umitseyhan75** [comment]
I now, your web site, it was written there that you are living in Canada. It is 23:50 here now.

**Comment by HACKERALERT** [comment]
Ah, great. Have a good night!

**Comment by HACKERALERT** [comment]
Alright, I'm ready for some translations :). Are you familiar with GitHub? I've created a `/translations/turkish.md` file, so if you're familiar with GitHub, you can edit the .md file and where it says "Translate below", that's where you can start translating to Turkish. When done (take your time), you can submit a PR and I'll merge it. If you're not familiar with Git, you can also translate the file I've attached and send it back to me as well. It's up to you! Thank you very much for your time, I really appreciate it. I'll be figuring out how to add localization support to Picocrypt itself, but in the meantime, you can help translate the main README.

[turkish.md](https://github.com/HACKERALERT/Picocrypt/files/6835516/turkish.md)

**Comment by umitseyhan75** [comment]
I don't see any "Translate below" section in the turkish.md. Am I missing something?

**Comment by HACKERALERT** [comment]
If you're forking it and then creating a PR, if you start editing the turkish.md, you'll see it. If you intend to just edit the attached file and send it back to me, then you won't see it because it's not there :). Thanks!

**Comment by umitseyhan75** [comment]
Please see the related [Pull Request](https://github.com/HACKERALERT/Picocrypt/pull/17).

**Comment by HACKERALERT** [comment]
Great. I'll let you know when I'm ready for translating of Picocrypt's UI to Turkish. I suspect that because I've never implemented it before, it might take a day or two to get things set up. Have a great night!

**Comment by HACKERALERT** [comment]
Oh, and to anyone that reads this, you can help me by translating to any language you choose, even if it's not listed as one on the homepage. The more languages, the closer to home it will be to people who don't natively speak English!

**Comment by umitseyhan75** [comment]
> 
> 
> Great. I'll let you know when I'm ready for translating of Picocrypt's UI to Turkish. I suspect that because I've never implemented it before, it might take a day or two to get things set up. Have a great night!

Waiting for it then!

Me thank you. I appreciate this project and your effort to make it real, want to help as much as I can.

**Comment by umitseyhan75** [comment]
I suggest you to create a Crowdin page for upcoimg Picocrypt translations.

**Comment by HACKERALERT** [comment]
Thanks for your suggestion, although I don't think the hassle is worth it currently, as there's only a README and some UI components to translate. I think as of now, a pull request will suffice for most translators and it doesn't require managing external secrets. If Picocrypt does start becoming much larger of a project, though, I will look into Crowdin again and see if it suits my needs. Thank you!

**Comment by HACKERALERT** [comment]
@umitseyhan75 There are many bugs that I believe I should fix as soon as possible, so I might get to translations a little later, in a week or two. So, you can sit back and relax, and I'll let you know when I'm ready.

**Comment by umitseyhan75** [comment]
Okay, take your time.

**Comment by umitseyhan75** [comment]
I think there may be a coise that comes by default which is "System Default" at top right Language selection box. This way, let's say my Windows is Turkish, so Picocrypt automatically opens Turkish.

**Comment by HACKERALERT** [comment]
I have no idea how I didn't think about that 🙄 ! That is a great idea and I think it should be rather easy to do. I'll make a note of it so I don't forget :) 

BTW, did your browser block Picocrypt? It seems in v1.13, many browsers block it. I changed some internals and v1.14 should not be blocked. Thanks!

**Comment by umitseyhan75** [comment]
Nope, same for v1.13. Never happend to me. Using Firefox 90.0.2 right now.

**Comment by HACKERALERT** [comment]
After much consideration, I've decided to not translate the UI itself, because it is reasonably simple to understand. Thus, this issue can be closed. The homepage will still be translated though, for easier reading.
