### ISSUE TITLE
How Does Plausible Deniability Work?

### ISSUE THREAD

**Issue by anon4747** [HACKERALERT/Picocrypt#160]
I read the following: _This can be useful in an authoritarian country where the only way to transport your files safely is if they don't "exist" in the first place._

If I use this option, I still see the file. Could you help me please? I'm trying hide a text file.

**Comment by HACKERALERT** [comment]
The feature doesn't delete the file, but it does obfuscate the volume. In other words, if you encrypt a text file with the deniability option, the output volume has nothing that indicates it is a volume. It looks like random data. Thus if you take the output volume with you, no one can prove that it contains data because it looks like random data, and so you can't legally be forced to disclose your password if there's nothing to decrypt in the first place.

**Comment by HACKERALERT** [comment]
Ah, that's a complexity for you to sort out. You can simple rename the volume and remove all extensions, including the `.pcv`. Sure, it may look a bit suspicious to have a file without any extensions, but no one can prove anything since the volume looks like random data.

**Comment by HACKERALERT** [comment]
A volume is just a file ending in `.pcv`. If you encrypt a file without deniability, the header format and metadata make it obvious that it's a Picocrypt volume. With the deniability option, there's nothing about the volume itself that hints it's a volume. Of course, because Picocrypt is simple, it can't achieve the level of deniability of VeraCrypt, but it does provide enough that you can't be forced to reveal your password, even if people suspect it may be a Picocrypt volume.

**Comment by HACKERALERT** [comment]
I'm not a legal expert, so take what I say with a grain of salt. However, I think you can assume that if a government knows your files are encrypted, they will find a legal reason to force you to reveal the key. However, if the government can't prove that you are in possession of encrypted files in the first place, they have no grounds to force you to decrypt your files. Anyways, it's a niche feature that hopefully no one will need to use. But if you do, it's there for use.

**Comment by HACKERALERT** [comment]
I'll close this for now since there's not much left for me to say. Feel free to open it again if you have further questions, though!

**Comment by hakavlad** [comment]
IMHO it's not "Plausible Deniability" at all. Indistinguishability from random data is a basic property of good ciphers and salts. 

Many of the file encryption programs create data that is indistinguishable from random data (for example, [ccrypt](https://en.wikipedia.org/wiki/Ccrypt), [kryptor](https://www.kryptor.co.uk/)). None of the authors of these programs call this property "plausible deniability".

If an attackers find files with random data on the disk, they will first of all think that this is an encrypted file. `picocrypt` does not provide the plausibility of denial.

>The underlying notion of deniable encryption is to be able to decrypt a cipher text into two different plaintexts depending on the key that is provided [1]. The purpose of this is to protect against adversaries who can force a user to provide a password to decrypt the cipher text, as the password that is provided will only reveal the decoy message while the true message remains hidden. 

-- https://ro.uow.edu.au/cgi/viewcontent.cgi?article=1954&context=eispapers1

Perhaps an appropriate name for the new feature would be "Preventing header metadata leaks".

**Comment by HACKERALERT** [comment]
Thank you for the clarification. Indeed my usage of 'plausible deniability'
doesn't match the definition that others use. I meant it in the sense that
no one can prove a file is a volume, so there's no basis to force someone
to decrypt it. Suspicion, of course, can't be prevented with the current
implementation. I didn't really consider how tools like VeraCrypt used the
term since Picocrypt is fundamentally different. The 'traditional'
plausible deniability can't be implemented in a file encryption tool like
Picocrypt because the decoy file sizes won't add up to the total volume
size, making it rather obvious that there is other data hidden. Thus, the
current implementation is the best I can do for Picocrypt. I don't think
"prevent header leaks" is a good term because the header doesn't really
leak any information other than following a specific format, and the goal
of the feature is still rooted in the same ideas as 'traditional' plausible
deniability. I also explain the feature in detail in the README, so there
shouldn't be any confusion as to what it does. So although my usage of
"plausible deniability" isn't the exact same as other interpretations, I
still think it's the most suitable term for Picocrypt.
