### ISSUE TITLE
"Cancel" has no effect

### ISSUE THREAD

**Issue by hakavlad** [HACKERALERT/Picocrypt#161]
![pico](https://i.imgur.com/ZyPNIZQ.png)
subj

**Comment by hakavlad** [comment]
And "Confirm password" is not requested (I can't check if the password entered is correct when decrypting).

**Comment by HACKERALERT** [comment]
Yeah this is just me being lazy and not wanting to add more case handling
code. I assumed that most people won't be encrypting more than 1GB in
deniability mode, but I guess not 🤷. Let me think about what to do about
this for a bit.

**Comment by HACKERALERT** [comment]
Okay, I'm deciding to not do anything about it. I think I've made it fairly clear in the documentation that the deniability feature is not for most people, so for the few who will need to use it, I think they can bear a few minutes of wait time for the benefit of deniability. I don't want to add too much new code for a feature that not many users will need. Also, I don't know if you already noticed, but the Cancel button is greyed out (intentionally), which is why it's not working/unresponsive.

**Comment by hakavlad** [comment]
OK thanks
