### ISSUE TITLE
Unable to decrypt file with no .pcv extension

### ISSUE THREAD

**Issue by hakavlad** [HACKERALERT/Picocrypt#162]
For example, `random.bin` is picocrypt encrypted file (with deniability). I dropped this file in picocrypt window and picocrypt suggests only `Encrypt` mode. I'd like to decrypt the file without renaming.

**Comment by BigPanda97** [comment]
How should it detect that the file is encrypted without the extension when using the "deniability" feature? 🤦🏻‍♂️

**Comment by hakavlad** [comment]
>How should it detect that the file is encrypted without the extension when using the "deniability" feature? 🤦🏻‍♂️

The user knows what the file is and must have two options - decrypt the file and encrypt the file. The standard extension is a bug, especially in the case of "deniable encryption" .

**Comment by HACKERALERT** [comment]
Adding both an encrypt and decrypt option is redundant. If you drop in a
file without .PCV, 99% of the time the user wants to encrypt it. For the
other 1%, I think it's reasonable to just add an extension, since as you
mentioned, the user knows it's a deniable volume, and decrypt it. Ideally
people shouldn't every need to use deniability, so it's best to keep
Picocrypt clean and simple for the majority of users.

**Comment by HACKERALERT** [comment]
Also, the standard .pcv extension for a deniable volume is not a bug.
People who need to use deniability will likely be smart enough to know to
rename the output file after encryption. So I'll leave that part to them
because if I choose a custom extension such as .bin instead, it's likely
the user will want to rename it again to suit their use case.

**Comment by hakavlad** [comment]
OK
