### ISSUE TITLE
picocrypt only uses the first 1 GB of the key file (and this is not documented)

### ISSUE THREAD

**Issue by hakavlad** [HACKERALERT/Picocrypt#168]
The first problem and unexpected behavior: it looks like picocrypt reads only the first 1 GiB of the key file. This can be seen from disk activity and from the fact that damage to the last part of a large key file does not lead to the impossibility of decryption.

Second problem and question: picoсrypt reports that it is reading a key file, but there is no disk activity. This can go on for tens of seconds. What happens during this time?

The third question: if piсocrypt reads only 1 GiB, why can it allocate SEVERAL gigabytes (see previous issues, picocrypt allocated 20G+) of memory?

"Reading keyfiles" when 1 GiB was already read:
![pico](https://i.imgur.com/5Zi4fLO.png)

The key file was 40 GB in size. Bottom line: only 1 GB read.
![pico](https://i.imgur.com/gCWTB8y.png)

**Comment by hakavlad** [comment]
The next question: why picocrypt uses 200% CPU and not read from the disk during "Reading keyfiles..."?

![pico](https://i.imgur.com/4kUXhOI.png)

**Comment by HACKERALERT** [comment]
There is too much "undefined" behaviour here for me to be able to tell what's going on, especially because I don't use Linux so I have no idea how memory management works in there.

Looking back at your initial screenshot in #165, it looks like your host OS correctly moves to swap when main memory is all used up, so I'm not sure why it isn't working here. Since you said the keyfile used was 40 GB, my guess would be that Picocrypt overloaded both the main and swap memory trying to allocate the memory required to store the keyfile. However, this should cause a crash as opposed to only reading the first 1 GB. Try using a 2 GB keyfile and modifying the last half to confirm whether this behaviour also holds or if it only happens when the total memory on the system is exhausted.

Looking at your GitHub profile, it seems like you have a good amount of programming expeience, so you should be able to following along with my code reasonably well even if you don't know Go. Below are two sections of code where the keyfile is hashed. In both cases, each keyfile is read entirely into memory before being hashed, so there's no reason why only the first 1 GB would be used:
https://github.com/HACKERALERT/Picocrypt/blob/main/src/Picocrypt.go#L1473
https://github.com/HACKERALERT/Picocrypt/blob/main/src/Picocrypt.go#L1488

From #165:
> In any case, the hashing of the files occurs in a sub-optimal way, and this can be corrected without breaking compatibility.

You are correct. I think the best solution to all of this weird behaviour is to just hash the keyfiles in chunks. It won't break compatibility as you mentioned, and should be much more memory efficient. I think I will keep this issue open (like the one about unencrypted comments) so that I will remember to fix this in the next release. I won't make a new release just yet though since I doubt many people are using 1+ GB keyfiles.

**Comment by HACKERALERT** [comment]
Yeah I'm not sure what's going on. But with all of this, I agree it'll be worth it to update the code to hash the keyfiles in chunks. So until I do that in the next release, I'll keep this issue open.

**Comment by HACKERALERT** [comment]
Added this to the changelog for the next release, so I'll close it here to keep things clean and organized.

**Comment by HACKERALERT** [comment]
Okay. I will fix this in the next release.
