### ISSUE TITLE
warning: 'setAllowedFileTypes:' is deprecated

### ISSUE THREAD

**Issue by pilinux** [HACKERALERT/Picocrypt#172]
`github.com/HACKERALERT/dialog/cocoa`

dlg.m:96:10: warning: 'setAllowedFileTypes:' is deprecated: first deprecated in macOS 12.0 - Use -allowedContentTypes instead [-Wdeprecated-declarations]

Perhaps you can fix it in `dialog/cocoa` repo? Thanks :)

**Comment by HACKERALERT** [comment]
I'm not sure how to fix it lol. I don't have a physical Mac or know how to code for its APIs. I also messed up the VM I use to compile and test on macOS, and I don't want to have to set another one up from scratch to Catalina, then upgrading. I don't think this is a big issue as I have a feeling that other things will break before this, since Monterey is still quite recent. I'm more worried about OpenGL and Rosetta 2 being removed. Until this becomes a breaking issue, I think it's fine to leave as is.
