### ISSUE TITLE
add random padding

### ISSUE THREAD

**Issue by sidielnikov** [HACKERALERT/Picocrypt#176]
hello Evan how do you like the idea that after encrypting the file, random padding would be added to it, like in kryptor?

https://github.com/samuel-lucas6/Kryptor/blob/master/src/Kryptor/FileEncryption/EncryptFile.cs

function "GetRandomPaddingLength"

and why encrypt the entire file in the Deniability function if you can encrypt, for example, 1 kilobyte from the beginning of the file where the header is located

**Comment by HACKERALERT** [comment]
I don't think random padding has that much use. The randomness adds a little bit of security I guess, but since I didn't implement it from the start, adding it now would cause compatibility issues with older volumes. For the deniability feature, I would've had to copy the rest of the file into a temporary file before decrypting anyways, so I might as well just do another layer of encryption for keeping the code and format relatively simple.
