### ISSUE TITLE
Nuitka / Numba ?

### ISSUE THREAD

**Issue by ink-splatters** [HACKERALERT/Picocrypt#3]
Hi,

thanks for awesome app! Still performance, unfortunately, is not the best... And you explain why.

Looks like Nuitka has significant performance gain vs CPython which in theory could add some extra speed:

[https://speedcenter.nuitka.net](https://speedcenter.nuitka.net)

There are more related projects, e.g. Numba looks promising: [https://numba.pydata.org](https://numba.pydata.org)

Would be glad to learn your opinion!

Cheers

**Comment by HACKERALERT** [comment]
Hey, thanks for your feedback! Are you encrypting with the Anti-Corruption feature? That feature is quite slow, and there's nothing I can do about it -- it's the way Reed Solomon works. On my Mac Mini Late 2012 running Windows 10, I can get ~60 MB/s encryption and decryption speeds without Anti-Corruption, which I think is reasonable. When I enable the Anti-Corruption feature, encryption is ~15 MB/s and decryption is about 1 MB/s. I know about Nuitka, but the output is huge. I don't think it is necessary because Picocrypt's core functions (encryption, decryption, hashing) is already implemented as a .pyd/.so, meaning that they are already transpiled to C and converted to a Python extension. I don't think using Nuitka would provide much benefit, since the core features are already fast. Would you mind describing your approximate speeds and the scenarios where they are produced? That would help me a lot. Thank you!

**Comment by HACKERALERT** [comment]
I'll close this now, but you may open it up again if you would like.
