### ISSUE TITLE
Automatically add encrypted file when .pcv file is opened with Picocrypt

### ISSUE THREAD

**Issue by Inrumpo** [HACKERALERT/Picocrypt#39]
I'm currently testing Picocrypt because I like the idea and functionality behind this lightweight tool. I believe my rather "non-techy" perspective can be of value (in terms of expectations and workflow).

This is a small one that would make working with Picocrypt a little easier.

## Usecase / Expectation
Windows lets users define programs to open files with specific file types/extensions. I've set Picocrypt to open `.pcv` files. My expectation when opening e.g. `EncryptedFolder123.zip.pcv` with Picocrypt is Picocrypt to open with most things prefilled and without the need to again select the file I want to decrypt.

## What actually happens
Double-clicking `EncryptedFolder123.zip.pcv` does open Picocrypt – that's it. It's the same as double-clicking the `Picocrypt.exe`. I still have to drag & drop `EncryptedFolder123.zip.pcv` into that newly opened window. 

## Environment

- Windows 10, 64bit
- Version 1.17 stable

**Comment by HACKERALERT** [comment]
Ah yes, I haven't yet added a file extension association and function for it yet. It's on my list of to-dos, so I should be able to properly associate extensions in v1.19 or v1.20. I'll keep this issue open until I get to doing that.

**Comment by HACKERALERT** [comment]
@Inrumpo I've implemented your feature and it seems to be working now. I've set it to automatically select any arguments and close automatically if encryption/decryption is a success. I've attached a preview below, let me know what you think!
[Picocrypt.zip](https://github.com/HACKERALERT/Picocrypt/files/7794328/Picocrypt.zip)

**Comment by Inrumpo** [comment]
> I've attached a preview below, let me know what you think!

Thanks for this build. I was able to test it. This does what I was thinking about (basically pre-selecting the .pcv file). Thanks! 👍

Some minor general UI things:

- The "confirm password" section is redundant when decrypting. Yes, it's greyed out, but it could be entirely absent. The same goes for the metadata section.
- "Start" could be changed to whatever I'm about to do; e.g. "decrypt now!" or "encrypt now!".

**Comment by HACKERALERT** [comment]
Thanks for letting me know! The auto-select feature will be available in the next release (v1.23).

As for your first point about the UI, indeed you are right. I've removed the confirm password prompt when decrypting and the changes should be reflected in the next release. The metadata section is supposed to show data when decrypting, so I'll keep that.

And for the "Start" button, also a great point, I've just implemented it to say "Encrypt" or "Decrypt" once a user drops files, and "Start" as an initial state. This will also be reflected in the next release.

I think this issue is good to close since everything is good to go. Let me know if you're okay with that!
