### ISSUE TITLE
Windows Version - Does not Open

### ISSUE THREAD

**Issue by CuteRose1** [HACKERALERT/Picocrypt#41]
Hello there ,
I am using 32 bit desktop computer with Windows 8.1 and I tried 7 releases of Picocrypt but some of them are not even compatible with my pc and the rest do not even open. I tried the installer version as well and it is successfully installed but does not open at all , no responses.

Is there any solution for this? 
And would you mind telling me the required system for this software to work? 
Mine is 32bit - Ram 2GB - CPU 2.5 Ghz & Windows 8.1

**Comment by HACKERALERT** [comment]
Hi,

This is because Picocrypt is compiled with 64-bit Go on a 64-bit system, so it probably won't work on your system as it currently stands. Are you familiar with building from source? If so, you can build from source using 32-bit Go, but otherwise, I'm afraid there's not much I can do since 32-bit systems are generally considered legacy.

**Comment by CuteRose1** [comment]
Hello again,

This is really disappointing , does that mean I cant use this software? :( 
What is building from the source? can you al least introduce a source so I could learn about it ? I couldnt find anything useful on Google.

by the way , isnt there any possible way you could make the 32 bit version as well? honestly I didnt get what you mean by legacy.

**Comment by HACKERALERT** [comment]
You might have a chance at running Picocrypt by building from source. Just go to https://github.com/HACKERALERT/Picocrypt/tree/main/src and follow the instructions to run Picocrypt. When downloading Go, make sure to download the 32-bit binary. I can't guarantee that this will work.

Making a 32-bit version work properly is very hard, because:
a) I'm on a 64-bit system, which is not natively 32-bit
b) I'm on Windows 11 which will cause issues with Windows 8.1
b) Picocrypt is compiled with 64-bit Golang
c) Picocrypt uses the `int64` data type which is 64-bit
d) OpenGL 3.2 is required and probably non-existent on 32-bit platforms
e) 32-bit has limited performance and only supports <2GB RAM
f) Picocrypt's dependencies are optimized for 64-bit/ARM systems
g) 32-bit CPUs don't have an acceleration like AVX2 and SSE3
h) I would have to fire up a Windows VM (license issues for 7/8/8.1)

Not trying to disappoint you, but this is just how things are, unfortunately. 32-bit systems are quite rare nowadays, and most modern apps don't support them, because it is difficult to do so for the reasons listed above. I would suggest you to use 7-Zip encryption in this scenario, because it's simple enough to use and has native 32-bit support.
