### ISSUE TITLE
Blake3 instead of Blake2b

### ISSUE THREAD

**Issue by BigPanda97** [HACKERALERT/Picocrypt#42]
You are currently using Blake2b in fast mode, but why not its successor, [Blake3](https://github.com/BLAKE3-team/BLAKE3)?
It is much faster as Blake2b, but at least as secure as SHA3. (See their comparison chart at their GitHub page.)

**Comment by whalehub** [comment]
Just adding to this, there exist at least two pure Go implementations of Blake3:

1. https://github.com/lukechampine/blake3
2. https://github.com/zeebo/blake3

**Comment by HACKERALERT** [comment]
Thanks for this suggestion. While BLAKE3 is a solid non-cryptographic checksum, it is not so good as a cryptographic hash function and as it stands, is not a good replacement for BLAKE2b.
> It is much faster as Blake2b, but at least as secure as SHA3.

That is not true. BLAKE3 is falsely advertising itself as being "at least as secure as SHA3". That is not true. I don't want to fill up my reply with jargon and opinionated matters, so I'll just leave it at this: _BLAKE3 has fewer rounds than BLAKE2 which has fewer rounds than BLAKE which was built on the relatively insecure SHA2. It is not as secure as SHA3, which has consistently been proven more secure over time. And since it has fewer rounds than BLAKE2, it is less secure. Also, it is not a standard and has no RFC like the others._

Also, it's worth noting that BLAKE2 is officially supported by Go, in the golang.org/x/crypto/blake2(b/s) module. These modules are maintained by the Go security team and are likely more reliable than a non-official implementation of BLAKE3.

So I won't be replacing BLAKE2b with BLAKE3. But thanks for the suggestions though!

**Comment by BigPanda97** [comment]
> While BLAKE3 is a solid non-cryptographic checksum

Technically, that's [not true](https://en.wikipedia.org/wiki/BLAKE_(hash_function)#BLAKE3). “BLAKE3 is a cryptographic hash function based on Bao and BLAKE2”. 

Also, “BLAKE3 is a single algorithm with many desirable features (parallelism, XOF, KDF, PRF and MAC)”
So, MAC is definitely possible with it, and it is also designed for it.

It is developed by the BLAKE team, which also made BLAKE (v1) and BLAKE2.
Yes, the security will be proven by time, but the whole BLAKE team recommends BLAKE3 now instead of Blake2.

**Comment by HACKERALERT** [comment]
I think I'll still stick with BLAKE2 because it has an official implementation and is most likely more secure than BLAKE3. There's also not much benefit because XChaCha20 itself can only go so fast, so the 6 GB/s speed won't have a major impact (a car with a fast motor doesn't make much of a difference when your wheels are tiny).
