### ISSUE TITLE
XChaCha20 Rationale

### ISSUE THREAD

**Issue by seaofmars** [HACKERALERT/Picocrypt#46]
Hi,

This is an interesting project, I understand the need for it. But I'd like to know why XChaCha20 was chosen over AES. I'm as much of a Bernstein fan as the next person, but I see almost no fair reason for this - particularly given Picocrypt has at least some performance concerns (i.e., fast mode) and AES' ubiquity in hardware implementations. There's no question XChaCha20 is significantly slower AES, and likely incurs a greater performance penalty over large amounts of data than using SHA3 over Blake2b. 

Thanks.

**Comment by HACKERALERT** [comment]
This is a very interesting question. You could look at it both ways. For example, AES has been around longer, and you can safely say that it has withstood the test of time, and is secure. By that same token though, ChaCha was designed around a decade later, using the modern stream construction with a modern design. ChaCha is also a very simple cipher, so it would be hard to hide a backdoor, or for a security issue to exist. Of course, Rijndael is also one of the simpler candidates during the AES competition. Thus, not much difference exists here.

Looking purely at the numbers, there are (theoretical) attacks on AES-256 for up to about 9 or 10 rounds, with AES-256 having 14 rounds total. ChaCha, on the other hand, only has 7 out of 20 rounds with attacks. So in terms of pure numbers, ChaCha might have an edge over AES, security-wise. Since Picocrypt's goal is to be secure now, and continue to be secure in the future, ChaCha20 is (IMO) the better choice, because an advance in computing power could put AES close to the edge of a cliff. ChaCha20, however, has a higher round count, as mentioned above, and also less attacks on higher round counts, so it would arguable hold up to quantum computing, etc., a little better than AES. Debateable of course, but I think ChaCha20 is the best choice here, where security, not performance, is the number one priority. ChaCha20 is also part of TLSv1.3, so it kind of ranks next to AES at least.

So overall, it is your choice. But for me and many of Picocrypt's users, ChaCha20 is the way to go. Questions are welcome!
