### ISSUE TITLE
More transparency

### ISSUE THREAD

**Issue by elesto** [HACKERALERT/Picocrypt#57]
I noticed Picocrypt tries to connect to the internet. It would be helpful to put this in the documentation and the reasons why.

**Comment by HACKERALERT** [comment]
Picocrypt connects to (and only to) https://raw.githubusercontent.com/HACKERALERT/Picocrypt/main/internals/version.txt to check if there is a new version available. It will never connect to any other site or domain. I don't think this needs to be mentioned because almost all modern software checks for updates automatically in one way or another, and Picocrypt doesn't collect any user info at all because I don't control GitHub's domain. Additionally, I plan to remove the update checker in future versions when Picocrypt is stable enough that any version will work.

**Comment by elesto** [comment]
I understand but It cant hurt to mention that it connects to github for updates somewhere on the page

**Comment by HACKERALERT** [comment]
@elesto Cool, I've added a quick note under the Security section in the README.
