### ISSUE TITLE
Virustotal hits

### ISSUE THREAD

**Issue by elesto** [HACKERALERT/Picocrypt#58]
The exe gets 5 hits on virustotal. It would be useful to try to fix this.

**Comment by HACKERALERT** [comment]
This is a very interesting topic because, by nature, Picocrypt is 80% cryptography, which could be easily mistaken for a crypto miner or ransomware. Unfortunately, there isn't much I can do on my end -- it's not like I can tell Avast to stop flagging Picocrypt and they would listen😄. This is a general problem for all open source projects, because some of the tools we use, like UPX (to compress executables), have been exploited by hackers in the past, so it's easy for antiviruses to believe that any program packaged with UPX is a virus. I could just release the plain compiled executable, which I've tested before and doesn't get any flags on VirusTotal, but the size is 11MB and UPX compresses it down a lot more. Another issue is with executable signing because unsigned executables (like Picocrypt) are statistically more likely to be malware. A signing certificate, however, costs upward of $300 a year to buy and renew, which is out of budget for Picocrypt and many other projects.

All in all, it's because of hackers that this is happening, and since I can't control hackers, there's not much I can do about this either. That's why I ask people to submit Picocrypt as a false positive in the Windows download section since the best case scenario is to have Picocrypt whitelisted.

**Comment by HACKERALERT** [comment]
BTW, the line that makes the network request is here: https://github.com/HACKERALERT/Picocrypt/blob/main/src/Picocrypt.go#L2188

**Comment by elesto** [comment]
Thanks, here is a [hybrid analysis](https://www.hybrid-analysis.com/sample/af56d009272ae08cbc312a9ef62f5541dbd8d76d011997ba7eac538b3352a6be) with maybe more information that you could use to cut down on flags.

**Comment by HACKERALERT** [comment]
Wow, I'm surprised at how sensitive antiviruses are getting. Like, why flag something just because it can detect mouse movements? I mean, that's how the GUI works lol. And how is reading the user locale for automatic translation malicious?

Anyway, thanks for letting me know, but there's really not much to be done.

**Comment by HACKERALERT** [comment]
BTW, if you are curious, I've attached an example of a plain executable that I don't pack with UPX. It gets zero flags on VirusTotal: https://www.virustotal.com/gui/file/26690e86b747d92153ffa3c44dc9c36abb048d3ea678e33c6282e470b7da94a1?nocache=1. So I guess it's a tradeoff... Do I want something that is tiny (3MB vs 10MB), or something that doesn't get flagged at all (even though the flags are from obscure vendors anyway)?

[Picocrypt.zip](https://github.com/HACKERALERT/Picocrypt/files/7875847/Picocrypt.zip)
