### ISSUE TITLE
Official Flatpak either along with or a replacement for snap

### ISSUE THREAD

**Issue by onymaticc** [HACKERALERT/Picocrypt#59]
Having an official Flatpak would be better than having a snap package.

Flatpaks work everywhere. Snaps only work on distros with systemd and app images require glibc.              

Secondly, snaps don't really provide better security than Flatpaks. Many security researchers who have criticized Flatpaks have also criticized snaps. At least flatpak have put effort into fixing these issues.

https://theevilskeleton.gitlab.io/2021/02/11/response-to-flatkill-org.html

Flatpak still has issues, but they are constantly improving and are much better at being a universal package manager than snap.

**Comment by HACKERALERT** [comment]
I see what you mean. I don't think it's fair to say that Flatpak is better than Snapcraft since they have their own pros and cons, but I actually wouldn't mind migrating to Flatpak. One of the things that made me choose Snapcraft was that its documentation is so much easier to understand and use than Flatpak's. Additionally, there are a lot of common bundles available in Snapcraft, like the gnome-3-38 extension, which automatically includes GTK3 build libraries and runtime libraries, X11/Wayland bindings, and OpenGL. When I was initially debating between Snapcraft, Flatpak, and AppImages, it became quite evident and that I could set up a snap in an hour, but had no idea how to deal with Flatpak or AppImages because they really only provide documentation for C, and Picocrypt is written in Go. Cross-platform OpenGL is hard enough, and bundling the correct packages is not easy. But Snapcraft worked and it worked well, which is why I chose it. I have nothing against Flatpak, but I'm not a Linux nerd either :)

If you are able to write a Flatpak manifest that works for Picocrypt, which includes supporting OpenGL 3.2, X11, and GTK3, then I would be happy to switch to it. But if you can't, I'm afraid I only have the time and effort to maintain a Snapcraft package, which is undoubtedly easier to package and distribute than Flakpak🥲.

**Comment by Etim-Orb** [comment]
https://www.reddit.com/r/linuxmasterrace/comments/sjg65v/why_flatpak_is_bad_and_how_to_fix_it/

I am personally would find Appimages the most useful for Tails for example.

**Comment by HACKERALERT** [comment]
I'm not sure what I should do now. I find Snapcraft simplest, @onymaticc thinks Flatpak has a better chance at becoming the standard package manager, and @Etim-Orb prefers portability. I'll just see what others have to say in this issue before I make a decision.

**Comment by Etim-Orb** [comment]
The ultimate decision is yours. If you stick with Snap for the time being, that's fine, since the software is still changing rapidly and down the road you can change or add new packaging to it. Ultimately I think you should decide whether it's worth the time and energy changing it right now.

**Comment by onymaticc** [comment]
I feel I should add a few things.

As I said above, app images are not really portable. They also don't even work on every distribution (take Void, Alpine and KISS for example). App images also don't auto update and don't really offer any security benefit.

> https://reddit.com/r/linuxmasterrace/comments/sjg65v/why_flatpak_is_bad_and_how_to_fix_it/

I want to discuss this link. Firstly, there is a GUI for managing flatpak permissions. It's called [Flatseal](https://flathub.org/apps/details/com.github.tchx84.Flatseal). Secondly, Flatpaks do have real sandboxing issues, however things are improving.

I understand if adding an official flatpak is too difficult, however I think it's something you should keep in mind for the future.

**Comment by HACKERALERT** [comment]
I'm definitely keeping Flatpak in mind, and I would like to migrate to it whenever it becomes within reach. It's not a top priority right now though, so I wouldn't worry too much about it now.

**Comment by HACKERALERT** [comment]
I'm going to close this for now, as I have tried numerous times and am unable to build a Flatpak for Picocrypt. The docs are lacking for Go, and there are no runtimes/extensions for Go or OpenGL. Snapcraft works well and is good enough for now. I don't plan to look into Flatpak any further, because I don't believe it is worth the amount of time and learning I would have to put in. If in the future, someone creates a Flatpak for Picocrypt, then I may decide to use it, but Snapcraft will be the default for the foreseeable future. At this point, it's easier to run from source than to install a Flatpak package anyway.
