### ISSUE TITLE
Feature Request: Command Line Support

### ISSUE THREAD

**Issue by Yur7y** [HACKERALERT/Picocrypt#7]
I'm really liking this project and would like to switch over from 7zip to this for creating encrypted backups of our company data. I currently have an autohotkey script that generates a password and then creates an encrypted 7z file using the command line interface. Is there any plans of bringing this kind of functionality to Picocrypt in the future? 

Thanks for the great work!

**Comment by HACKERALERT** [comment]
Yes! See https://github.com/HACKERALERT/Picocrypt/blob/main/Roadmap.md#under-consideration, which is the Roadmap for Picocrypt and contains potential new features. CLI is there already. Glad you enjoy Picocrypt! Consider donating some spare change to help me raise money to audit Picocrypt :)

**Comment by HACKERALERT** [comment]
If we're all good, you can close this issue.

**Comment by JoeMamaAME** [comment]
+1

https://github.com/HACKERALERT/Picocrypt/blob/main/Roadmap.md#under-consideration
This link no longer leads to anywhere, is there a new roadmap available?

**Comment by HACKERALERT** [comment]
@JoeMamaAME After careful consideration, I deleted the section because I don't believe adding a CLI will be of much benefit, especially considering that the UI is one of Picocrypt's main strengths. For a secure and automatable CLI tool, I would recommend Kryptor, which is a CLI encryption tool that uses similar cryptography as Picocrypt.

**Comment by HACKERALERT** [comment]
@YMan84

In a spark of motivation, I've finally added a simple CLI to Picocrypt! Let me know what you think.

https://github.com/HACKERALERT/Picocrypt/tree/main/cli
