### ISSUE TITLE
[macOS] Download via AppStore

### ISSUE THREAD

**Issue by beerisgood** [HACKERALERT/Picocrypt#70]
It would be awesome if this program can be downloaded at Apple AppStore so it can be used with „AppStore only“ setups.

**Comment by HACKERALERT** [comment]
I don't exactly trust the Apple Store or Microsoft Store because it's really simple for a rogue employee to insert a backdoor into Pico's source, compile it, and then replace the good version in the store with the backdoored one. When you get the executables directly from me, however, that is not a problem.

Regardless, thanks for letting me know, I will take a look at the Apple docs and I'll keep you posted on any progress.

**Comment by HACKERALERT** [comment]
Hmm, a certificate is $100 per year...

**Comment by HACKERALERT** [comment]
@beerisgood Publishing Picocrypt to the Mac App Store seems too difficult and expensive. I would have to pay $100 for a signing certificate that I would need to renew every year, and I don't have a real macOS device that can compile properly for the App Store (my VirtualBox macOS is not sufficient). So I will not be taking on this endeavour, because the benefits are not worth the significant costs.
