### ISSUE TITLE
Extremely slow decrypt ? 

### ISSUE THREAD

**Issue by Minibus93** [HACKERALERT/Picocrypt#79]
Hello, 

I was trying out Picocrypt, so I took a folder (2.3GB) and encrypted it with Picocrypt. I used the Reed Solomon feature since my goal is long term cloud storage.
Encryption was kinda slow, but I suppose that's normal considering that the tooltip on reed solomon warns you "slow).
Anyway, this is not an issue, it took about 10min to encrypt which is fine for me.

However, when I tried to decrypt said file (2.6GB after encryption with RS) it was very very very slow. The ETA was of 5 hours!
![Immagine](https://user-images.githubusercontent.com/73554423/163348906-82b9db02-fc8e-4e6b-9a25-e23c5ec534cd.png)

What's going on here? I don' think this behavior is normal/working as intended

Some info about me:

OS: Windows 10 Home 21H2 Build 19044.1586
CPU Intel(R) Core(TM) i5-1035G1 CPU @ 1.00GHz   1.19 GHz
RAM 8,00 GB 
Picocrypt version 1.25

Even if in the screenshot you see the force decrypt option ticked, I first tried with the simple decrypt, but it was slow in the same way.
So, before opening this, I tried with the "force decrypt" option ticked hoping it would have speed up things.
However, no success.

**Comment by HACKERALERT** [comment]
It's a known issue actually, and has been for a while. That's about the same decrypting speed I get on my machine as well. Reed-Solomon itself is slow, so it's is kind of expected, however, there should be room for improvement, since when Picocrypt was written in Python, I could still get 1MB/s decode. I've already looked into this, but it seems there is no trivial solution. I'll look at it again though, since it's the only thing left on my to-do list.

"Force decrypt" simply keeps the output if Picocrypt detects the volume has been modified. There are two cases where a volume would be modified: an adversary maliciously modifying the volume, or the file corrupting really badly. In both cases, Picocrypt will delete the decrypted files to keep the user safe. Force Decrypt tells Picocrypt to keep the output.

**Comment by Minibus93** [comment]
I see, I wasn't aware this was a known issue otherwise I wouldn't have opened another post, my bad. 

Thanks for the effort! :D

**Comment by HACKERALERT** [comment]
No worries, it is a big issue so I'll keep this issue open until I can figure something out.

**Comment by HACKERALERT** [comment]
I have an idea. Maybe when decrypted a RS-encoded volume, Picocrypt can decrypt it "normally" the first time, ignoring the parity bytes and decrypting as if RS wasn't used. When the decryption is done and the checksums don't match, then we know corruption has occurred, so then I can set Picocrypt to run again, but this time to actually use the parity bytes to correct the data. Using this method would give us the best of both worlds... If there is no corruption, the file will decrypt at normal speeds (like if RS wasn't used), and only if corruption is detected, will Picocrypt correct the broken bytes.

**Comment by Minibus93** [comment]
Well, mhhh, I guess that anything is better than current status, however I don't consider myself expert enough to say which is the best practice here :/

Maybe someone more adeguate than me can express their thoughts on this

**Comment by HACKERALERT** [comment]
I gave it a quick test and I can get a nice 20MB/s decode for the first pass. Don't worry about the details, I just thought you may find it interesting. I'll continue with the changes and I'll put a test file here when I'm done.

**Comment by HACKERALERT** [comment]
I've made a few adjustments so now by default, Picocrypt will assume there is no corruption and decrypt at regular (non-RS) speeds for a RS-encoded volume, and only if the checksums don't match, will Picocrypt actually try to rebuild the broken bytes with the slower speed. So if there is no corruption, a RS-encoded volume will decrypt with the same speed as a non-RS volume 🚀. And if there is corruption, just be happy that at least your data can almost certainly be recovered without a scratch.

I'm releasing v1.28 today which will contain this update. Here's a test in the meantime, if you are curious to try it: [Picocrypt.zip](https://github.com/HACKERALERT/Picocrypt/files/8647936/Picocrypt.zip)

**Comment by HACKERALERT** [comment]
I've made many adjustments and now the RS decoder is much smoother (the progress bar is constantly updated instead of the large interval gap present in v1.27) and should be slightly better performing. I think I've made all the improvements possible for RS, so I'll close this issue now. I'm sure you will find what you hope for in the next release :)
