### ISSUE TITLE
Having ".pcv" anywhere in the file path/name breaks the application when encrypting.

### ISSUE THREAD

**Issue by openstampede** [HACKERALERT/Picocrypt#8]
If the string ".pcv" exists in the file name (for example: test.pcv.test.txt), the application silently fails to properly select the chosen file with no error message. If ".pcv" is in the path instead (for example: /home/user/test.pcv/testing.txt), the file can be selected, but the application throws an "unknown error" when the Start button is clicked.

Using simple file extension checks to determine whether to encrypt or decrypt works in a lot of cases, but is a bit fragile. A more robust method might be to silently include some non-encrypted metadata in any encrypted file, something the application can look for when a file is selected, that will tell Picocrypt if it's a compatible, encrypted file. Doing that would break the ability to encrypt a file twice... but I'm not sure how many people would need to do that. :)

**Comment by HACKERALERT** [comment]
Lol, I just realized the issue a couple seconds before you created the issue. I've fixed it by checking the the file ends in ".pcv", which will fix all the cases you described. It will be out in the next version (v1.11). I'll close the issue since I've solved it, but feel free to reopen if you see necessary. Cheers!
