### ISSUE TITLE
Random filename

### ISSUE THREAD

**Issue by kgyl** [HACKERALERT/Picocrypt#97]
Can you add encrypted filenames as well or at least the optionality for random filename?

**Comment by HACKERALERT** [comment]
What would be the benefit?

**Comment by kgyl** [comment]
When you are uploading the files to a cloud storage or file sharing site, it automatically obfuscates the additional available information (which makes things easier).

**Comment by HACKERALERT** [comment]
I see. But if the information is encrypted, why is there a need to use a random filename? If you have a bunch of encrypted volumes on a cloud storage with random filenames and you want to find a file in one of them, are you going to try every single volume? I think random/encrypted filenames would add complexity and since Picocrypt focuses on simplicity, I don't see a significant benefit. You can also rename before encrypting and you can always generate a random filename through the password generator with alphanumeric categories selected.

**Comment by kgyl** [comment]
You could also say the same about password generation & Reed-Solomon, they just add complexity.

I think just using the same random string generator which is used for password could work perfectly.

**Comment by HACKERALERT** [comment]
That's a fair point. I'll see what I can do and if it doesn't take too much time or code, I will add a "Randomize" button.

**Comment by HACKERALERT** [comment]
There's not enough space in the UI to add it. I don't find it very useful anyway. But thanks for the suggestion.

**Comment by kgyl** [comment]
Thanks for the tool :)
